# Generated by Django 3.2.12 on 2022-02-11 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0002_clock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockedHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.IntegerField()),
                ('current_week', models.IntegerField()),
                ('current_month', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='clock',
            name='clocked_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clock',
            name='clocked_out',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
